language: objective-c
xcode_workspace: Ultimaterugby.xcworkspace
xcode_scheme: UltimaterugbyTests
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

